### ISSUE TITLE
this appears to be for passthrough only, any got sharing working?

### ISSUE THREAD

**Issue by zombiehoffa** [isc30/ryzen-7000-series-proxmox#14]
It would be handy to have the onboard hdmi still output in case vmbr0 fails to come up, as it has a few times. At the same time I would like to have the gpu available for transcoding for plex/jellyfin/etc.

**Comment by isc30** [comment]
Yeah, if you want sharing via `/dev/dri/renderDXXX` you can follow this guide: https://github.com/TheHellSite/proxmox_tutorials/tree/main/lxc_gpu_passthrough

**Comment by zombiehoffa** [comment]
Hey, thanks, I'm not sure why I didn't think of that as a possible solution to sharing  the gpu with the base proxmox system. I am pretty sure it 100% solves my problem.

**Comment by isc30** [comment]
haha no problem, i also ended up doing that for LXC (jellyfin) for simplicity and because the AMD reset bug is a pain
