### ISSUE TITLE
[Addition] The vbios for 7950X also works for 7900X

### ISSUE THREAD

**Issue by engels74** [isc30/ryzen-7000-series-proxmox#40]
Hey - thanks for hosting the repository. Worked flawlessly on my Ubuntu VM, through Unraid.

I just wanted to add, that the `vbios_7950x.bin` also works for the AMD 7900X CPU, as they both share the same iGPU (Raphael).
I tested it with both Plex and Immich on my AMD 7900X, and both use the iGPU automatically, using the vbios for 7950X.

Thought it would make sense to add that it also works for 7900X to the readme/description

Thanks

**Comment by isc30** [comment]
hey I'm happy to accept PRs and that way you can also appear as a contributor to the repo :)
