### ISSUE TITLE
cannot create vbios binary files

### ISSUE THREAD

**Issue by supernova4420** [isc30/ryzen-7000-series-proxmox#44]
cpu: AMD Ryzen 5 5700G

I have successfully confirmed using 'lspci -nnk' that the 'Kernel driver in Use' for my GPU is 'vfio-pci'.

But cannot create vbios binary files. When I run 'gcc vbios.c -o vbios' (after pasting the correct contents in the vbios.c file), the contents of the output vbios file is:

^?ELF^B^A^A^@^@^@^@^@^@^@^@^@^C^@>^@^A^@^@^@�^P^@^@^@^@^@^@@^@^@^@^@^@^@^@x8^@^@^@^@^@^@^@^@^@^@@^@8^@
^@@^@^_^@^^^@^F^@^@^@^D^@^@^@@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@�^B^@^@^@^@^@^@�^B^@^@^@^@^@^@^H^@^@^@^@^@^@^@^C^@^@^@^D^@^@^@^X^C^@^@^@^@^@^@^X^C^@^@>^@^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@c^@^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@�^@^@^@ ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@M^@^@^@"^@^@^@^@^@^@^>^@^@^@^@^@^@^@^@^@^@^@8@^@^@^@^@^@^@^G^@^@^@^K^@^@^@^@^@^@^@^@^@^@^@@@^@^@^@^@^@^@^G^@^@^@^L^@^@^@^@^@^@^@^@^@^@^@H@^@^@^@^@^@^@^G^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@>/^@^@f�^@^@^@^@^@^@^@^@1�I��^H��H���PTE1�1�H�=�^@^@^@�^U�.^@^@�f.^O^_�^@^@^@^@^@^O^_@^@H�=I/^@^@H�^EB/^@^@H9�t^UH�^E�.^@^@H��t  ��^O^_�^@^@^@^@�^O^_�^@^@^@^@H�=>�
^@^@H��H�Ǹ^@^@^@^@�����������2^B^@^@H�E؋@4�E�H�E؋@^D�EԋU�H�E�H��H�������H�E�H�}�^@u^\H������H�^@H��������������^A^@^@�E�H�X��E�H�P�H�E�H�xLH�E�H���^A^@^@^@�^T��>^_
^@^@H��H�Ǹ^@^@^@^@�'����������^A^@^@H�E�H��������b^A^@^@�U�H�E�H^A�H�E�H�E�H�E�H�E��@^X��^O�K^A^@^@H�E�^O�@^N^O��H�E�^O�@^L^O��H������A�ȉ�H�^U�^L^@^@�^@^D^@^@H�>^@^@^@^@^@^@^@^@%s: failed to read VFCT body!
^@vbios_%x_%x.bin^@wb^@^@^@^@^@^@^@%s: failed to dump vbios %x:%x
^@dump vbios %x:%x to %s
^@^A^[^C;,^@^@^@^D^@^@^@X���x^@^@^@^H����^@^@^@^X���H^@^@^@^A����^@^@^@^@^@^@^@^T^@^@^@^@^@^@^@^AzR^@^Ax^P^A^[^L^G^H�^A^G^P^T^@^@^@^\^@^@^@����"^@^@^@^@^@^@^@^@>^FH�^C^C
^C^L^G^H^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@>^@^@^@^@^@^@^@�^T^@^@^@^@^@^@^Y^@^@^@^@^@^@^@�=^@^@^@^@^@^@^[^@^@^@^@^@^@^@^H^@^@^@^@^@^@^@^Z^@^@^@^@^@^@^@�=^@^@^@^@^@^@^\^@^@^@^@^@^@^@^H^@^@^@^@^@^@^@���o^@^>^@^@^@^@^@^@^@�^@^@^@^@^@^@^@^K^@^@^@^@^@^@^@^X^@^@^@^@^@^@^@^U^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^C^@^@^@^@^@^@^@�?^@^@^@^@^@^@^B^@^@^@^@^@^@^@�^@^@^@^@^@^@^@^T^@^@>^B^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^]^B^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@0^B^@^@^Q^B^Y^@`@^@^@^@^@^@^@^@^@^@^@^@^@^@^@<^B^@^@ ^@^@^@^@^@^@^>

Can see a 'failed to read VFCT body' and 'failed to dump vbios' errors.

Any help would be appreciated.

**Comment by mntyfrsh** [comment]
Why not use the 5700U vbios that is in the repo? The 5700U is a low power version of the 5700G.

**Comment by supernova4420** [comment]
That worked! However I was not aware that the AMD reset but existed on linux too. Does the fix linked in the readme work for linux as well as windows?

**Comment by mntyfrsh** [comment]
Supposedly fixed by Linux kernel v5.9. Otherwise use https://github.com/gnif/vendor-reset.

Please close this issue as the content is going off the rails.

**Comment by mntyfrsh** [comment]
> That worked! However I was not aware that the AMD reset but existed on linux too. Does the fix linked in the readme work for linux as well as windows?

Supposedly fixed by Linux kernel v5.9. Otherwise use https://github.com/gnif/vendor-reset.

Admin - Please close this issue as the discussed content is going off the rails and has nothing to do with the topic the issue was opened regarding.
